config/routes.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :agile_queries, :only => [:new, :create]
  resources :agile_versions, :only => [:index] do
    post :index, :on => :collection
  end
end

resources :agile_versions, :only => [:update, :show] do
  collection do
    get 'load'
    get 'autocomplete'
  end
end

resources :issues do
  get "done_ratio", :to => "agile_journal_details#done_ratio"
  get "status", :to => "agile_journal_details#status"
  get "assignee", :to => "agile_journal_details#assignee"
end

resources :agile_queries
get '/agile_colors/:object_type', :to => "agile_colors#index", :as => "agile_colors"
put '/agile_colors/:object_type', :to => "agile_colors#update", :as => "update_agile_colors"

get '/projects/:project_id/agile/charts', :to => "agile_charts#show", :as => "project_agile_charts"
get '/agile/charts/', :to => "agile_charts#show", :as => "agile_charts"
get '/agile/charts/render_chart', :to => "agile_charts#render_chart"
get '/agile/charts/select_version_chart', :to => "agile_charts#select_version_chart"
get '/projects/:project_id/agile/board', :to => 'agile_boards#index'
get '/agile/board', :to => 'agile_boards#index'
put '/agile/board', :to => 'agile_boards#update', :as => 'update_agile_board'
get '/agile/issue_tooltip', :to => 'agile_boards#issue_tooltip', :as => 'issue_tooltip'
get '/agile/inline_comment', :to => 'agile_boards#inline_comment', :as => 'agile_inline_comment'
post 'projects/:project_id/agile/create_issue', :to => 'agile_boards#create_issue', :as => 'agile_create_issue'

app/models/agile_query.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

class AgileQuery < Query
  unloadable

  attr_reader :truncated

  self.queried_class = Issue
  self.view_permission = :view_issues if Redmine::VERSION.to_s >= '3.4'

  self.available_columns = [
    QueryColumn.new(:id, :sortable => "#{Issue.table_name}.id", :default_order => 'desc', :caption => :label_agile_issue_id),
    QueryColumn.new(:project, :groupable => "#{Issue.table_name}.project_id", :sortable => "#{Project.table_name}.id"),
    QueryColumn.new(:tracker, :sortable => "#{Tracker.table_name}.position", :groupable => true),
    QueryColumn.new(:estimated_hours, :sortable => "#{Issue.table_name}.estimated_hours"),
    QueryColumn.new(:done_ratio, :sortable => "#{Issue.table_name}.done_ratio"),
    QueryColumn.new(:priority, :sortable => "#{IssuePriority.table_name}.position", :default_order => 'desc', :groupable => true),
    QueryColumn.new(:author, :sortable => lambda {User.fields_for_order_statement("users")}, :groupable => true),
    QueryColumn.new(:category, :sortable => "#{IssueCategory.table_name}.name", :groupable => "#{Issue.table_name}.category_id"),
    QueryColumn.new(:fixed_version, :sortable => lambda {Version.fields_for_order_statement}, :groupable => "#{Issue.table_name}.fixed_version_id"),
    QueryColumn.new(:start_date, :sortable => "#{Issue.table_name}.start_date"),
    QueryColumn.new(:due_date, :sortable => "#{Issue.table_name}.due_date"),
    QueryColumn.new(:created_on, :sortable => "#{Issue.table_name}.created_on"),
    QueryColumn.new(:updated_on, :sortable => "#{Issue.table_name}.updated_on"),
    QueryColumn.new(:thumbnails, :caption => :label_agile_board_thumbnails),
    QueryColumn.new(:description),
    QueryColumn.new(:sub_issues, :caption => :label_agile_sub_issues),
    QueryColumn.new(:day_in_state, :caption => :label_agile_day_in_state),
    QueryColumn.new(:parent, :groupable => "#{Issue.table_name}.parent_id", :sortable => "#{AgileData.table_name}.position", :caption => :field_parent_issue),
    QueryColumn.new(:assigned_to, :sortable => lambda {User.fields_for_order_statement}, :groupable => "#{Issue.table_name}.assigned_to_id"),
    QueryColumn.new(:relations, :caption => :label_related_issues),
    QueryColumn.new(:last_comment, :caption => :label_agile_last_comment),
    QueryColumn.new(:story_points, :caption => :label_agile_story_points)
  ]

  if RedmineAgile.use_checklist?
    self.available_columns << QueryColumn.new(:checklists, :caption => :label_checklist_plural)
  end
  before_save :set_default_when_appropriate

  scope :visible, lambda {|*args|
    user = args.shift || User.current
    base = Project.allowed_to_condition(user, :view_issues, *args)
    scope = eager_load(:project).where("#{table_name}.project_id IS NULL OR (#{base})")

    if user.admin?
      scope.where("#{table_name}.visibility <> ? OR #{table_name}.user_id = ?", VISIBILITY_PRIVATE, user.id)
    elsif user.memberships.any?
      scope.where("#{table_name}.visibility = ?" +
        " OR (#{table_name}.visibility = ? AND #{table_name}.id IN (" +
          "SELECT DISTINCT q.id FROM #{table_name} q" +
          " INNER JOIN #{table_name_prefix}queries_roles#{table_name_suffix} qr on qr.query_id = q.id" +
          " INNER JOIN #{MemberRole.table_name} mr ON mr.role_id = qr.role_id" +
          " INNER JOIN #{Member.table_name} m ON m.id = mr.member_id AND m.user_id = ?" +
          " WHERE q.project_id IS NULL OR q.project_id = m.project_id))" +
        " OR #{table_name}.user_id = ?",
        VISIBILITY_PUBLIC, VISIBILITY_ROLES, user.id, user.id)
    elsif user.logged?
      scope.where("#{table_name}.visibility = ? OR #{table_name}.user_id = ?", VISIBILITY_PUBLIC, user.id)
    else
      scope.where("#{table_name}.visibility = ?", VISIBILITY_PUBLIC)
    end
  }

  def initialize(attributes=nil, *args)
    super attributes
    unless Redmine::VERSION.to_s > '2.4'
      self.filters ||= { 'status_id' => {:operator => "*", :values => [""]} }
    end
    self.filters ||= { }
    @truncated = false
  end

  def card_columns
    self.inline_columns.select{|c| !%w(day_in_state tracker thumbnails description assigned_to done_ratio spent_hours estimated_hours project id sub_issues checklists last_comment story_points).include?(c.name.to_s)}
  end

  def visible?(user=User.current)
    return true if user.admin?
    return false unless project.nil? || user.allowed_to?(:view_issues, project)
    case visibility
    when VISIBILITY_PUBLIC
      true
    when VISIBILITY_ROLES
      if project
        (user.roles_for_project(project) & roles).any?
      else
        Member.where(:user_id => user.id).joins(:roles).where(:member_roles => {:role_id => roles.map(&:id)}).any?
      end
    else
      user == self.user
    end
  end

  def is_private?
    visibility == VISIBILITY_PRIVATE
  end

  def is_public?
    !is_private?
  end

  def color_base
    options[:color_base] || RedmineAgile.color_base
  end

  def color_base=(value)
    options[:color_base] = value
  end
  def is_default?
    !!options[:is_default]
  end

  def is_default=(value)
    options[:is_default] = !!value
  end

  def set_as_default
    AgileQuery.where(:project_id => self.project_id).where(:visibility => self.visibility).where("#{AgileQuery.table_name}.id <> ?", self.id).each do |query|
      query.is_default = false
      query.save
    end if self.is_default?
  end

  def self.default_query(project=nil)
    board_scope = AgileQuery.visible
    board_scope = board_scope.where(:project_id => project)
    default_query = board_scope.where("#{table_name}.visibility = ? AND #{table_name}.user_id = ?", VISIBILITY_PRIVATE, User.current).detect{|q| q.is_default?}
    default_query ||= board_scope.eager_load(:user => :memberships).where("#{table_name}.visibility = ?", VISIBILITY_ROLES).detect{|q| q.is_default?}
    default_query ||= board_scope.where("#{table_name}.visibility = ?", VISIBILITY_PUBLIC).detect{|q| q.is_default?}
    default_query
  end

  def build_from_params(params)
    if params[:fields] || params[:f]
      self.filters = {}
      add_filters(params[:fields] || params[:f], params[:operators] || params[:op], params[:values] || params[:v])
    else
      available_filters.keys.each do |field|
        add_short_filter(field, params[field]) if params[field]
      end
    end
    self.group_by = params[:group_by] || (params[:query] && params[:query][:group_by])
    self.column_names = params[:c] || (params[:query] && params[:query][:column_names])
    self.color_base = params[:color_base] || (params[:query] && params[:query][:color_base])
    self.is_default = params[:is_default] || (params[:query] && params[:query][:is_default])
    self.draw_relations = params[:draw_relations] || (params[:query] && params[:query][:draw_relations])
    if params[:f_status] || params[:wp]
      self.options = options.merge({ :f_status => params[:f_status], :wp => params[:wp] })
    end
    self
  end

  # Builds a new query from the given params and attributes
  def self.build_from_params(params, attributes={})
    new(attributes).build_from_params(params)
  end

  def initialize_available_filters
    principals = []
    subprojects = []
    versions = []
    categories = []
    issue_custom_fields = []

    if project
      principals += project.principals.sort
      unless project.leaf?
        subprojects = project.descendants.visible.all
        principals += Principal.member_of(subprojects)
      end
      versions = project.shared_versions.all
      categories = project.issue_categories.all
      issue_custom_fields = project.all_issue_custom_fields
    else
      if all_projects.any?
        principals += Principal.member_of(all_projects)
      end
      versions = Version.visible.where(:sharing => 'system').all
      issue_custom_fields = IssueCustomField.where(:is_for_all => true)
    end
    principals.uniq!
    principals.sort!
    users = principals.select {|p| p.is_a?(User)}

    unless Redmine::VERSION.to_s > '2.4'
      add_available_filter "status_id",
        :type => :list_status, :values => IssueStatus.sorted.collect{|s| [s.name, s.id.to_s] }
    end

    if project.nil?
      project_values = []
      if User.current.logged? && User.current.memberships.any?
        project_values << ["<< #{l(:label_my_projects).downcase} >>", "mine"]
      end
      project_values += all_projects_values
      add_available_filter("project_id",
        :type => :list, :values => project_values
      ) unless project_values.empty?
    end

    add_available_filter "tracker_id",
      :type => :list, :values => trackers.collect{|s| [s.name, s.id.to_s] }
    add_available_filter "priority_id",
      :type => :list, :values => IssuePriority.all.collect{|s| [s.name, s.id.to_s] }

    author_values = []
    author_values << ["<< #{l(:label_me)} >>", "me"] if User.current.logged?
    author_values += users.collect{|s| [s.name, s.id.to_s] }
    add_available_filter("author_id",
      :type => :list, :values => author_values
    ) unless author_values.empty?

    assigned_to_values = []
    assigned_to_values << ["<< #{l(:label_me)} >>", "me"] if User.current.logged?
    assigned_to_values += (Setting.issue_group_assignment? ?

app/controllers/agile_queries_controller.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

class AgileQueriesController < ApplicationController
  unloadable

  menu_item :agile

  before_filter :find_query, :except => [:new, :create, :index]
  before_filter :find_optional_project, :only => [:new, :create]

  include QueriesHelper
  helper :queries
  helper :agile_boards

  def index
    @limit = per_page_option
    @query_count = AgileQuery.visible.count
    @query_pages = Paginator.new @query_count, @limit, params['page']
    @queries = AgileQuery.visible.
                    order("#{Query.table_name}.name").
                    limit(@limit).
                    offset(@offset).
                    all
  end

  def new
    @query = AgileQuery.new
    @query.user = User.current
    @query.project = @project
    @query.visibility = AgileQuery::VISIBILITY_PRIVATE unless User.current.allowed_to?(:manage_public_queries, @project) || User.current.admin?
    @query.build_from_params(params)
  end

  def create
    @query = AgileQuery.new(params[:query])
    @query.user = User.current
    @query.project = params[:query_is_for_all] ? nil : @project
    @query.visibility = AgileQuery::VISIBILITY_PRIVATE unless User.current.allowed_to?(:manage_public_queries, @project) || User.current.admin?
    @query.build_from_params(params)
    @query.column_names = nil if params[:default_columns]

    if @query.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to_agile_board(:query_id => @query)
    else
      render :action => 'new', :layout => !request.xhr?
    end
  end

  def edit
  end

  def update
    @query.attributes = params[:query]
    @query.project = nil if params[:query_is_for_all]
    @query.visibility = AgileQuery::VISIBILITY_PRIVATE unless User.current.allowed_to?(:manage_public_queries, @project) || User.current.admin?
    @query.build_from_params(params)
    @query.column_names = nil if params[:default_columns]
    if @query.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to_agile_board(:query_id => @query)
    else
      render :action => 'edit'
    end
  end

  def destroy
    @query.destroy
    redirect_to_agile_board(:set_filter => 1)
  end

private
  def find_query
    @query = AgileQuery.find(params[:id])
    @project = @query.project
    render_403 unless @query.editable_by?(User.current)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_optional_project
    @project = Project.find(params[:project_id]) if params[:project_id]
    render_403 unless User.current.allowed_to?(:add_agile_queries, @project, :global => true)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def redirect_to_agile_board(options)
    if @project
      redirect_to agile_board_path(options.merge(:project_id => @project))
    else
      redirect_to agile_board_path(options)
    end
  end
end

app/views/agile_queries/_columns.html.erb
<table class="query-columns">
  <tr>
    <td style="padding-left:0">
      <%= label_tag "available_columns", l(:description_available_columns) %>
      <br />
      <%= select_tag 'available_columns',
              options_for_select(query_available_inline_columns_options(query)),
              :multiple => true, :size => 10, :style => "width:150px",
              :ondblclick => "moveOptions(this.form.available_columns, this.form.selected_columns);" %>
    </td>
    <td class="buttons">
      <input type="button" value="&#8594;"
       onclick="moveOptions(this.form.available_columns, this.form.selected_columns);" /><br />
      <input type="button" value="&#8592;"
       onclick="moveOptions(this.form.selected_columns, this.form.available_columns);" />
    </td>
    <td>
      <%= label_tag "selected_columns", l(:description_selected_columns) %>
      <br />
      <%= select_tag tag_name,
              options_for_select(query_selected_inline_columns_options(query)),
              :id => 'selected_columns', :multiple => true, :size => 10, :style => "width:150px",
              :ondblclick => "moveOptions(this.form.selected_columns, this.form.available_columns);" %>
    </td>
    <td class="buttons">
      <input type="button" value="&#8593;" onclick="moveOptionUp(this.form.selected_columns);" /><br />
      <input type="button" value="&#8595;" onclick="moveOptionDown(this.form.selected_columns);" />
    </td>
  </tr>
</table>

<%= javascript_tag do %>
$(document).ready(function(){
  $('.query-columns').closest('form').submit(function(){
    $('#selected_columns option').prop('selected', true);
  });
});
<% end %>

app/views/agile_queries/_filters.html.erb
<%= javascript_tag do %>
var operatorLabels = <%= raw_json Query.operators_labels %>;
var operatorByType = <%= raw_json Query.operators_by_filter_type %>;
var availableFilters = <%= raw_json query.available_filters_as_json %>;
var labelDayPlural = <%= raw_json l(:label_day_plural) %>;
var allProjects = <%= raw_json query.all_projects_values %>;
$(document).ready(function(){
  initFilters();
  <% query.filters.each do |field, options| %>
  addFilter("<%= field %>", <%= raw_json query.operator_for(field) %>, <%= raw_json query.values_for(field) %>);
  <% end %>
});
<% end %>

<table style="width:100%">
<tr>
<td>
<table id="filters-table">
</table>
</td>
<td class="add-filter" style="width: initial;">
<%= label_tag('add_filter_select', l(:label_filter_add)) %>
<%= select_tag 'add_filter_select', filters_options_for_select(query), :name => nil %>
</td>
</tr>
</table>
<%= hidden_field_tag 'f[]', '' %>
<% include_calendar_headers_tags %>

app/views/agile_queries/_form.html.erb
<%= error_messages_for 'query' %>

<div class="box">
<div class="tabular">
  <%= hidden_field_tag 'gantt', '1' if params[:gantt] %>

  <p><label for="query_name"><%=l(:field_name)%></label>
  <%= text_field 'query', 'name', :size => 80 %></p>

  <% if User.current.admin? || User.current.allowed_to?(:manage_public_agile_queries, @project) %>
    <% if Redmine::VERSION.to_s < "2.4" %>
      <p><label for="query_is_public"><%=l(:field_is_public)%></label>
      <%= check_box 'query', 'is_public',
            :onchange => (User.current.admin? ? nil : 'if (this.checked) {$("#query_is_for_all").removeAttr("checked"); $("#query_is_for_all").attr("disabled", true);} else {$("#query_is_for_all").removeAttr("disabled");}') %></p>
    <% else %>
      <p><label><%=l(:field_visible)%></label>
        <label class="block"><%= radio_button 'query', 'visibility', Query::VISIBILITY_PRIVATE %> <%= l(:label_visibility_private) %></label>
        <label class="block"><%= radio_button 'query', 'visibility', Query::VISIBILITY_ROLES %> <%= l(:label_visibility_roles) %>:</label>
        <% Role.givable.sorted.each do |role| %>
          <label class="block role-visibility"><%= check_box_tag 'query[role_ids][]', role.id, @query.roles.include?(role), :id => nil %> <%= role.name %></label>
        <% end %>
        <label class="block"><%= radio_button 'query', 'visibility', Query::VISIBILITY_PUBLIC %> <%= l(:label_visibility_public) %></label>
        <%= hidden_field_tag 'query[role_ids][]', '' %>
      </p>
    <% end %>
  <% end %>

  <p><label for="query_is_for_all"><%=l(:field_is_for_all)%></label>
  <%= check_box_tag 'query_is_for_all', 1, @query.project.nil?,
        :disabled => (!@query.new_record? && (@query.project.nil? || (@query.is_public? && !User.current.admin?))) %></p>
  <% if Redmine::VERSION.to_s > "2.4" %>
    <p>
      <label>
        <%= l(:label_agile_default_board) %>
      </label>
      <%= check_box_tag 'query[is_default]', 1, @query.is_default? %>
    </p>
  <% end %>
  <fieldset><legend><%= l(:label_options) %></legend>
    <p><label for="query_default_columns"><%=l(:label_agile_board_default_fields)%></label>
    <%= check_box_tag 'default_columns', 1, @query.has_default_columns?, :id => 'query_default_columns',
          :onclick => 'if (this.checked) {$("#columns").hide();} else {$("#columns").show();}' %></p>

    <% if RedmineAgile.use_colors? && @query.respond_to?(:color_base) %>
      <p><label for='color_base'><%= l(:label_agile_color_based_on) %></label>
      <%= select 'query', 'color_base', options_for_select(options_card_colors_for_select(@query.color_base)) %></p>
    <% end %>
    <p><label for="query_group_by"><%= l(:label_agile_swimlanes) %></label>
      <%= select 'query', 'group_by', @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]}, :include_blank => true %>
    </p>
  </fieldset>
</div>

<fieldset id="filters"><legend><%= l(:label_filter_plural) %></legend>
<%= render :partial => 'agile_queries/filters', :locals => {:query => query}%>
</fieldset>

<% if Redmine::VERSION.to_s > '2.4' %>
  <%= content_tag 'fieldset', :class => "card-fields" do %>
  <legend><%= l(:label_agile_board_columns) %></legend>
  <%= render_board_fields_status(query) %>
  <% end %>
<% end %>


<%= content_tag 'fieldset', :id => 'columns', :style => (query.has_default_columns? ? 'display:none;' : nil), :class => "card-fields" do %>
<legend><%= l(:label_agile_fields) %></legend>
<%= render_board_fields_selection(query) %>
<% end %>

</div>

<%= javascript_tag do %>
$(document).ready(function(){
  $("input[name='query[visibility]']").change(function(){
    var checked = $('#query_visibility_1').is(':checked');
    $("input[name='query[role_ids][]'][type=checkbox]").attr('disabled', !checked);
  }).trigger('change');
});
<% end %>

app/views/agile_queries/edit.html.erb
<h2><%= l(:label_agile_board_edit) %></h2>

<%= form_tag(agile_query_path(@query), :method => :put) do %>
  <%= render :partial => 'form', :locals => {:query => @query} %>
  <%= submit_tag l(:button_save) %>
<% end %>

app/views/agile_queries/index.html.erb
<div class="contextual">
<%= link_to l(:label_query_new), new_agile_query_path(:project_id => @project), :class => 'icon icon-add' if User.current.allowed_to?(:add_agile_queries, nil, :global => true)%>
</div>

<h2><%= l(:label_agile_board_plural) %></h2>

<% if @queries.empty? %>
  <p><i><%=l(:label_no_data)%></i></p>
<% else %>
  <table class="list">
  <% @queries.each do |query| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td class="name">
        <%= link_to h(query.name), :controller => 'agile_boards', :action => 'index', :project_id => query.project_id, :query_id => query %>
      </td>
      <td class="buttons">
        <% if query.editable_by?(User.current) %>
        <%= link_to l(:button_edit), edit_agile_query_path(query), :class => 'icon icon-edit' %>
        <%= delete_link agile_query_path(query) %>
      <% end %>
      </td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/agile_queries/new.html.erb
<h2><%= l(:label_agile_board_new) %></h2>

<%= form_tag(@project ? project_agile_queries_path(@project) : agile_queries_path) do %>
  <%= render :partial => 'form', :locals => {:query => @query} %>
  <%= submit_tag l(:button_save) %>
<% end %>