config/routes.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :agile_queries, :only => [:new, :create]
  resources :agile_versions, :only => [:index] do
    post :index, :on => :collection
  end
end

resources :agile_versions, :only => [:update, :show] do
  collection do
    get 'load'
    get 'autocomplete'
  end
end

resources :issues do
  get "done_ratio", :to => "agile_journal_details#done_ratio"
  get "status", :to => "agile_journal_details#status"
  get "assignee", :to => "agile_journal_details#assignee"
end

resources :agile_queries
get '/agile_colors/:object_type', :to => "agile_colors#index", :as => "agile_colors"
put '/agile_colors/:object_type', :to => "agile_colors#update", :as => "update_agile_colors"

get '/projects/:project_id/agile/charts', :to => "agile_charts#show", :as => "project_agile_charts"
get '/agile/charts/', :to => "agile_charts#show", :as => "agile_charts"
get '/agile/charts/render_chart', :to => "agile_charts#render_chart"
get '/agile/charts/select_version_chart', :to => "agile_charts#select_version_chart"
get '/projects/:project_id/agile/board', :to => 'agile_boards#index'
get '/agile/board', :to => 'agile_boards#index'
put '/agile/board', :to => 'agile_boards#update', :as => 'update_agile_board'
get '/agile/issue_tooltip', :to => 'agile_boards#issue_tooltip', :as => 'issue_tooltip'
get '/agile/inline_comment', :to => 'agile_boards#inline_comment', :as => 'agile_inline_comment'
post 'projects/:project_id/agile/create_issue', :to => 'agile_boards#create_issue', :as => 'agile_create_issue'

app/views/settings/agile/_general.html.erb
<p>
  <label><%= l(:label_agile_board_items_limit) %></label>
  <%= text_field_tag 'settings[board_items_limit]', RedmineAgile.board_items_limit, :size => 3 %>
</p>
<p>
  <label for="settings_status_colors"><%= l(:label_agile_status_colors) %></label>
  <%= hidden_field_tag 'settings[status_colors]', 0, :id => nil %>
  <%= check_box_tag 'settings[status_colors]', 1, RedmineAgile.status_colors? %>
</p>

<p>
  <label><%= l(:label_agile_color_based_on) %></label>
  <%= select_tag 'settings[color_on]', options_card_colors_for_select(@settings["color_on"]) %> <%= link_to l(:label_agile_manage_colors), agile_colors_path("tracker") %>
</p>

<p>
  <label><%= l(:label_agile_board_default_fields) %></label>
  <%= select_tag 'settings[default_columns]', options_for_select(AgileQuery.new(:column_names => RedmineAgile.default_columns).available_columns.collect{|column| [column.caption, column.name]}, RedmineAgile.default_columns), :multiple => true, :include_blank => true, :size => 10, :style => "width:150px" %>
</p>

<p>
  <label><%= l(:label_agile_esitmate_units) %></label>
  <%= select_tag 'settings[estimate_units]', options_for_select(RedmineAgile::ESTIMATE_UNITS.map{ |eu| [l("label_agile_#{eu}"), eu] }, 
    RedmineAgile.estimate_units), :onchange => "toggleTrackerForSP(this); return false" %>
  <script type="text/javascript">
    function toggleTrackerForSP (node) {
      if ($(node).val() == 'story_points')
        $('#trackers_for_sp').show();
      else
        $('#trackers_for_sp').hide();
    }
  </script>
</p>
<div id="trackers_for_sp" style="display:<%= RedmineAgile.use_story_points? ? 'block' : 'none' %>">
  <p>
    <label><%= l(:label_agile_trackers_for_sp) %></label>
    <%= select_tag 'settings[trackers_for_sp]', options_for_select(Tracker.all.map{|tr| [tr.name, tr.id]}, RedmineAgile.trackers_for_sp), :prompt => "All", :style => "width:150px" %>
  </p>
</div>
<p>
  <label><%= l(:label_agile_default_chart) %></label>
  <%= select_tag 'settings[default_chart]', options_charts_for_select(RedmineAgile.default_chart) %>
</p>

<p>
  <label for="settings_exclude_weekends"><%= l(:label_agile_exclude_weekends) %></label>
  <%= hidden_field_tag 'settings[exclude_weekends]', 0, :id => nil %>
  <%= check_box_tag 'settings[exclude_weekends]', 1, RedmineAgile.exclude_weekends? %>
</p>

<p>
  <label><%= l(:label_agile_time_reports_items_limit) %></label>
  <%= text_field_tag 'settings[time_reports_items_limit]', RedmineAgile.time_reports_items_limit, :size => 3 %>
</p>
<p>
  <label for="settings_hide_closed_issues_data"><%= l(:label_agile_hide_closed_issues_data) %></label>
  <%= check_box_tag 'settings[hide_closed_issues_data]', 1, RedmineAgile.hide_closed_issues_data? %>
</p>
<p>
  <label><%= l(:label_agile_allow_create_cards) %></label>
  <%= hidden_field_tag 'settings[allow_create_card]', 0, :id => nil %>
  <%= check_box_tag 'settings[allow_create_card]', 1, RedmineAgile.allow_create_card? %>
</p>
<p>
  <label for="settings_auto_assign_on_move"><%= l(:label_agile_auto_assign_on_move) %></label>
  <%= hidden_field_tag 'settings[auto_assign_on_move]', 0, :id => nil %>
  <%= check_box_tag 'settings[auto_assign_on_move]', 1, RedmineAgile.auto_assign_on_move? %>
</p>

<p>
  <label for="settings_allow_inline_comments"><%= l(:label_agile_inline_comment) %></label>
  <%= hidden_field_tag 'settings[allow_inline_comments]', 0, :id => nil %>
  <%= check_box_tag 'settings[allow_inline_comments]', 1, RedmineAgile.allow_inline_comments? %>
</p>