config/routes.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :agile_queries, :only => [:new, :create]
  resources :agile_versions, :only => [:index] do
    post :index, :on => :collection
  end
end

resources :agile_versions, :only => [:update, :show] do
  collection do
    get 'load'
    get 'autocomplete'
  end
end

resources :issues do
  get "done_ratio", :to => "agile_journal_details#done_ratio"
  get "status", :to => "agile_journal_details#status"
  get "assignee", :to => "agile_journal_details#assignee"
end

resources :agile_queries
get '/agile_colors/:object_type', :to => "agile_colors#index", :as => "agile_colors"
put '/agile_colors/:object_type', :to => "agile_colors#update", :as => "update_agile_colors"

get '/projects/:project_id/agile/charts', :to => "agile_charts#show", :as => "project_agile_charts"
get '/agile/charts/', :to => "agile_charts#show", :as => "agile_charts"
get '/agile/charts/render_chart', :to => "agile_charts#render_chart"
get '/agile/charts/select_version_chart', :to => "agile_charts#select_version_chart"
get '/projects/:project_id/agile/board', :to => 'agile_boards#index'
get '/agile/board', :to => 'agile_boards#index'
put '/agile/board', :to => 'agile_boards#update', :as => 'update_agile_board'
get '/agile/issue_tooltip', :to => 'agile_boards#issue_tooltip', :as => 'issue_tooltip'
get '/agile/inline_comment', :to => 'agile_boards#inline_comment', :as => 'agile_inline_comment'
post 'projects/:project_id/agile/create_issue', :to => 'agile_boards#create_issue', :as => 'agile_create_issue'

app/helpers/agile_boards_helper.rb
# encoding: utf-8
#
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

module AgileBoardsHelper
  def agile_color_class(issue, options={})
    if options[:color_base]
      color = case options[:color_base]
      when AgileColor::COLOR_GROUPS[:issue]
        issue.color
      when AgileColor::COLOR_GROUPS[:tracker]
        issue.tracker.color
      when AgileColor::COLOR_GROUPS[:priority]
        issue.priority.color
      when AgileColor::COLOR_GROUPS[:spent_time]
        AgileColor.for_spent_time(issue.estimated_hours, issue.spent_hours)
      when AgileColor::COLOR_GROUPS[:project]
        issue.project.color
      end
    else
      color = if RedmineAgile.tracker_colors?
        issue.tracker.color
      elsif RedmineAgile.issue_colors?
        issue.color
      elsif RedmineAgile.priority_colors?
        issue.priority.color
      elsif RedmineAgile.spent_time_colors?
        AgileColor.for_spent_time(issue.estimated_hours, issue.spent_hours)
      end
    end
    "#{RedmineAgile.color_prefix}-#{color}" if color && RedmineAgile.use_colors?
          end

  def agile_user_color(user, options={})
    return if Redmine::VERSION.to_s < '2.4'
    user_color = user.color rescue nil
    user_color ||= AgileColor.for_user(user.login)
    if options[:color_base]
      "border-left: 5px solid #{user_color}".html_safe if options[:color_base] ==  AgileColor::COLOR_GROUPS[:user]
    elsif RedmineAgile.user_color?
      "border-left: 5px solid #{user_color}".html_safe
    end
  end

  def header_th(name, rowspan = 1, colspan = 1, leaf = nil)
    th_attributes = {}
    if leaf
      # th_attributes[:style] = ""
      th_attributes[:style] = "border-bottom: 4px solid; border-bottom-color: #{color_by_name(leaf.name)};" if RedmineAgile.status_colors?
      th_attributes[:"data-column-id"] = leaf.id
      issue_count = leaf.instance_variable_get("@issue_count") || 0
      if Redmine::VERSION.to_s > '2.4'
        wp_count = leaf.instance_variable_get("@wp_max")
        unless wp_count.blank?
          th_attributes[:class] = leaf.wp_class
          issue_count_tag = content_tag(:span, issue_count, :class => leaf.wp_class)
          count_tag = " (#{content_tag(:span, issue_count_tag + "/#{wp_count}", :class => 'count')})".html_safe
        else
          count_tag = " (#{content_tag(:span, issue_count.to_i, :class => 'count')})".html_safe
        end
      else
        count_tag = " (#{content_tag(:span, issue_count.to_i, :class => 'count')})".html_safe
      end
            

      # estimated hours total
      story_points_count = leaf.instance_variable_get("@story_points") || 0
      hours_count = leaf.instance_variable_get("@estimated_hours_sum") || 0
      if story_points_count > 0
        hours_tag = " #{content_tag(:span, (story_points_count).to_s + 'sp',
          :class => 'hours', :title => l(:field_estimated_hours))}".html_safe
      else
        hours_tag = " #{content_tag(:span, ("%.2fh" % hours_count.to_f).to_s,
        :class => 'hours', :title => l(:field_estimated_hours))}".html_safe if hours_count > 0
      end
    end
    th_attributes[:rowspan] = rowspan if rowspan > 1
    th_attributes[:colspan] = colspan if colspan > 1
    content_tag :th, h(name) + count_tag + hours_tag, th_attributes
  end

  def render_board_headers(columns)
    tree = HeaderTree.new

    columns.map do |column|
      path = column.name.split(':').map(&:strip)
      tree.put path, column
    end

    # puts tree

    maxdepth = tree.depth

    ret = tree.render

    ret[1..-1].map do |row|
      row.map do |th_params|
        header_th *th_params
      end
    end.map{|x| "<tr>#{x.join('')}</tr>" }.join.html_safe
          end

  def color_by_name(name)
    "##{"%06x" % (name.unpack('H*').first.hex % 0xffffff)}"
  end
  def format_swimlane_object(object, html=true)
    case object.class.name
    when 'Array'
      object.map {|o| format_swimlane_object(o, html)}.join(', ').html_safe
    when 'Time'
      format_time(object)
    when 'Date'
      format_date(object)
    when 'Fixnum'
      object.to_s
    when 'Float'
      sprintf "%.2f", object
    when 'User'
      html ? link_to_user(object) : object.to_s
    when 'Project'
      html ? link_to_project(object) : object.to_s
    when 'Version'
      html ? link_to(object.name, version_path(object)) : object.to_s
    when 'TrueClass'
      l(:general_text_Yes)
    when 'FalseClass'
      l(:general_text_No)
    when 'Issue'
      object.visible? && html ? link_to_issue(object) : "##{object.id}"
    else
      html ? h(object) : object.to_s
    end
  end

  def render_board_fields_selection(query)
    query.available_inline_columns.reject(&:frozen?).reject{ |c| c.name == :story_points && !RedmineAgile.use_story_points? }.map do |column|
      label_tag('', check_box_tag('c[]', column.name, query.columns.include?(column)) + column.caption, :class => "floating" )
    end.join(" ").html_safe
  end

  def render_board_fields_status(query)
    current_statuses = query.options[:f_status] || IssueStatus.where(:is_closed => false).pluck(:id).map(&:to_s)
    wp = query.options[:wp] || {}
    status_tags = IssueStatus.sorted.map do |status|
      content_tag(:span,
        label_tag('', check_box_tag('f_status[]', status.id, current_statuses.include?(status.id.to_s)
        ) + content_tag(:span, status.to_s), :title => status.to_s) + text_field_tag("wp[#{status.id}]", wp[status.id.to_s],
          :size => 5, :class => 'wp_input', :placeholder => "WIP",
          :title => l(:label_agile_wip_limit)), :class => 'floating'
      )
                end.join(' ').html_safe
    hidden_field_tag('f[]', 'status_id').html_safe +
      hidden_field_tag('op[status_id]', "=").html_safe +
      status_tags
  end

  def coefficient
    if @project.try(:id).nil?
      coef = 1
      return
    end
    settings = TabSetting.get_settings(@project.id)
    coef = settings['main']['role_coef'].gsub(',','.')
    coef = 1 if coef == '0' || coef == nil
    coef = 1 unless User.current.allowed_to?(:use_role_coef, @project) && !User.current.admin?
    coef
  end

  def render_issue_card_hours(query, issue)
    coef = coefficient
    hours = []
    hours << "%.2f" % (issue.total_spent_hours.to_f*coef.to_f) if query.has_column_name?(:spent_hours) && issue.total_spent_hours > 0
    hours << "%.2f" % (issue.estimated_hours.to_f*coef.to_f) if query.has_column_name?(:estimated_hours) && issue.estimated_hours
    hours = [hours.join('/') + "h"] unless hours.blank?
    hours << "#{issue.story_points}sp" if query.has_column_name?(:story_points) && issue.story_points

    content_tag(:span, "(#{hours.join('/')})", :class => 'hours') unless hours.blank?
  end

  def agile_progress_bar(pcts, options={})
    pcts = [pcts, pcts] unless pcts.is_a?(Array)
    pcts = pcts.collect(&:round)
    pcts[1] = pcts[1] - pcts[0]
    pcts << (100 - pcts[1] - pcts[0])
    width = options[:width] || '100px;'
    legend = options[:legend] || ''
    content_tag('table',
      content_tag('tr',
        (pcts[0] > 0 ? content_tag('td', '', :style => "width: #{pcts[0]}%;", :class => 'closed') : ''.html_safe) +
        (pcts[1] > 0 ? content_tag('td', '', :style => "width: #{pcts[1]}%;", :class => 'done') : ''.html_safe) +
        (pcts[2] > 0 ? content_tag('td', '', :style => "width: #{pcts[2]}%;", :class => 'todo') : ''.html_safe) +
        (legend ? content_tag('td', content_tag('p', legend, :class => 'percent'), :class => 'legend') : ''.html_safe)
      ), :class => "progress progress-#{pcts[0]}", :style => "width: #{width};").html_safe
  end

  def issue_children(issue)
    return unless issue.children.any?
    content_tag :ul do
      issue.children.select{ |x| x.visible? }.each do |child|
        id = if @query.has_column_name?(:tracker) || @query.has_column_name?(:id) then "##{child.id}:&nbsp;" else '' end
        concat "<li class='#{'task-closed' if child.closed?}'><a href='#{issue_path(child)}'>#{id}#{child.subject}</a></li>#{issue_children(child)}".html_safe
      end
    end
  end

  def time_in_state(distance=nil)
    return "" if !distance || !(distance.is_a? Time)
    distance = Time.now - distance
    hours = distance/(3600)
    return "#{I18n.t('datetime.distance_in_words.x_hours', :count => hours.to_i)}" if hours < 24
    "#{I18n.t('datetime.distance_in_words.x_days', :count => (hours/24).to_i)}"
  end

  def class_for_closed_issue(issue)
    return '' if !RedmineAgile.hide_closed_issues_data?
    return 'closed-issue' if issue.closed?
    ''
  end

  def init_agile_tooltip_info(options={})
    js_code = "function callGetToolTipInfo()
      {
        var url = '#{issue_tooltip_url}';
        agileBoard.getToolTipInfo(this, url);
      }
      $('.tooltip').mouseenter(callGetToolTipInfo);
    "
    return js_code.html_safe if options[:only_code]
    javascript_tag(js_code)
  end

  def show_checklist?(issue)
    RedmineAgile.use_checklist? && issue.checklists.any? && User.current.allowed_to?(:view_checklists, issue.project)
  rescue
    false
  end


end

app/views/agile_boards/_add_issue_card.html.erb
<% if User.current.allowed_to?(:add_issues, @project, :global => true) && @project && RedmineAgile.allow_create_card? && @project.trackers.any? %>
  <div class="add-issue">
    <input class="new-card__input" placeholder='<%= l(:label_agile_add_new_issue) %>' >
  </div>
<% end %>

app/views/agile_boards/_index.html.erb
<div class="contextual">
<% if !@query.new_record? && @query.editable_by?(User.current) %>
  <%= link_to l(:button_edit), edit_agile_query_path(@query), :class => 'icon icon-edit' %>
  <%= delete_link agile_query_path(@query) %>
<% end %>
</div>

<h2><%= @query.new_record? ? l(:label_agile_board) : h(@query.name) %></h2>
<% html_title(@query.new_record? ? l(:label_agile_board) : @query.name) %>

<%= form_tag({ :controller => 'agile_boards', :action => 'index', :project_id => @project },
            :method => :get, :id => 'query_form', :onsubmit => 'DisableNullFields()') do %>
  <div id="query_form_with_buttons" class="hide-when-print">
    <%= hidden_field_tag 'set_filter', '1' %>
    <div id="query_form_content">
      <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
        <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
        <div style="<%= @query.new_record? ? "" : "display: none;" %>">
          <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
        </div>
      </fieldset>
      <fieldset class="collapsible collapsed">
        <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
        <div style="display: none;">
          <table class="options">
            <% if Redmine::VERSION.to_s > '2.4' %>
              <tr>
                <td>
                  <%= l(:label_agile_board_columns) %>
                </td>
                <td class="card-fields">
                  <%= render_board_fields_status(@query) %>
                </td>
              </tr>
            <% end %>
            <tr>
              <td><%= l(:label_agile_fields) %></td>
              <td class="card-fields">
                <%= render_board_fields_selection(@query) %>
              </td>
            </tr>
            <tr>
              <td><label for='group_by'><%= l(:label_agile_swimlanes) %></label></td>
              <td><%= select_tag('group_by',
                                 options_for_select(
                                   [[]] + @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]},
                                   @query.group_by)
                         ) %></td>
            </tr>
            <% if RedmineAgile.use_colors? && @query.respond_to?(:color_base) %>
              <tr>
                <td><label for='color_base'><%= l(:label_agile_color_based_on) %></label></td>
                <td><%= select_tag 'color_base', options_card_colors_for_select(@query.color_base) %></td>
              </tr>
            <% end %>
          </table>
        </div>
      </fieldset>
    </div>
    <p class="buttons">
    <div class="contextual">
      <%= link_to_function l(:label_agile_fullscreen), '$("html").toggleClass("agile-board-fullscreen"); saveFullScreenState()', :class => 'icon icon-fullscreen' %>
    </div>
    <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
    <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project }, :class => 'icon icon-reload'  %>
    <% if @query.new_record? && User.current.allowed_to?(:add_agile_queries, @project, :global => true) %>
        <%= link_to_function l(:button_save),
                             "$('#query_form').attr('action', '#{ @project ? new_project_agile_query_path(@project) : new_agile_query_path }').submit()",
                             :class => 'icon icon-save' %>
    <% end %>
    </p>

  </div>
<% end %>

<%= error_messages_for 'query' %>
<% if @query.valid? %>
  <% if @issues.empty? || @board_columns.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <% if @query.truncated %>
      <p class="warning"><%= l(:label_agile_board_truncated, :max => RedmineAgile.board_items_limit) %></p>
    <% end %>
    <%= render :partial => 'board' %>
  <% end %>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'issues_links' %>
  <% if @project && @project.assignable_users.any? %>
    <%= render :partial => 'members' %>
  <% end %>
  <%= render :partial => 'agile_charts/agile_charts' %>
<% end %>

<% html_title l(:label_agile_board) %>
<%= javascript_tag "agileContextMenuInit('#{ url_for(issues_context_menu_path) }')" %>
<% content_for :header_tags do %>
  <%= javascript_include_tag "redmine_agile", :plugin => 'redmine_agile' %>
  <%= javascript_include_tag "jquery.ui.touch-punch.js", :plugin => 'redmine_agile' %>
  <%= javascript_include_tag "visibility.min.js", :plugin => 'redmine_agile' %>
  <%= javascript_include_tag "redmine_agile_context_menu", :plugin => 'redmine_agile' %>
  <%= stylesheet_link_tag 'context_menu' %>
  <%= stylesheet_link_tag "redmine_agile.css", :plugin => "redmine_agile", :media => "print" %>
<% end %>
<% if User.current.allowed_to?(:edit_issues, @project, :global => true) %>
  <script type="text/javascript">
    var agileBoard = new AgileBoard({
      project_id: '<%= @project && @project.id %>',
      update_agile_board_path: '<%= escape_javascript update_agile_board_path %>',
      issues_path: '<%= escape_javascript issues_path %>',
      create_issue_path: '<%= escape_javascript(agile_create_issue_path(:project_id => @project)) if @project %>'
    });
  </script>
<% end %>

app/views/agile_boards/_issue_card.html.erb
<div class="issue-card hascontextmenu <%= agile_color_class(issue, :color_base => @query.respond_to?(:color_base) && @query.color_base) %> <%= class_for_closed_issue(issue) %>" data-id="<%= issue.id %>" style="<%= agile_user_color(issue.assigned_to, :color_base => @query.respond_to?(:color_base) && @query.color_base) if issue.assigned_to %>">
    <% if issue.closed? && RedmineAgile.hide_closed_issues_data? %>
      <span class="fields">
         <div class="tooltip">
           <p class="issue-id <%= 'without-tracker' if @query.has_column_name?(:tracker).blank? %>">
               <strong><%= link_to "#{'#' + issue.id.to_s}", issue_path(issue) %></strong>
            </p>
            <span class="tip">
            </span>
          </div>
      </span>
    <% else %>
      <span class="fields">
          <% if User.current.allowed_to?(:edit_issues, @project, :global => true) && RedmineAgile.allow_inline_comments?  %>
            <div class="quick-edit-card">
              <%# link_to image_tag("/images/edit.png"), edit_issue_path(issue), :class => "", :style => "margin-right: 3px;", :title => l(:button_edit) %>
              <%= link_to image_tag("/images/comment.png", :alt => "Edit"), "#", :onclick => "showInlineComment(this, '#{j(agile_inline_comment_path(:id => issue))}'); return false;", :title => l(:label_comment_add), :class => 'add-comment' %>
            </div>
          <% end %>
          <% if @query.has_column_name?(:project) %>
            <p class="project">
              <%= issue.project.name %>
            </p>
          <% end %>
          <p class="issue-id <%= 'without-tracker' if @query.has_column_name?(:tracker).blank? %>">
            <%= check_box_tag("ids[]", issue.id, false, :id => nil, :class => 'checkbox') %>
            <% if @query.has_column_name?(:tracker) %>
              <strong><%= issue_heading(issue) %></strong>
            <% end %>
            <%= render_issue_card_hours(@query, issue) %>
          </p>
          <p class="name" ><%= link_to "#{'#' + issue.id.to_s + ': ' if @query.has_column_name?(:id) && @query.has_column_name?(:tracker).blank?}#{issue.subject.truncate(100)}", issue_path(issue) %></p>
          <p class="attributes">
            <% @query.card_columns.select{|c| !c.value(issue).blank? }.each do |column| %>
              <b><%= column.caption %></b>: <%= column_content(column, issue) %> <br>
            <% end %>
          </p>

          <% if @query.has_column_name?(:day_in_state) %>
            <p class="attributes">
                <b><%= " #{I18n.t('label_agile_day_in_state')}: " %></b>
                <% find_change_state = false %>
                <% if @query.journals_for_state %>
                  <% @query.journals_for_state.each do |journal| %>
                    <% if journal.journalized_id == issue.id %>
                      <%= time_in_state(journal.created_on) %>
                      <% find_change_state = true %>
                      <% break %>
                    <% end %>
                  <% end %>
                <% end %>

                <% if !find_change_state %>
                  <%= time_in_state(issue.day_in_state) %>
                <% end %>
            </p>
          <% end %>

          <% if @query.has_column_name?(:description) && !issue.description.blank? %>
            <em class="info description">
              <%= issue.description.truncate(200) %>
            </em>
          <% end %>
          <% if @query.has_column_name?(:sub_issues) && issue.sub_issues.any? %>
            <div class='sub-issues'>
              <%= issue_children(issue) %>
            </div>
          <% end %>
          <% if @query.has_column_name?(:thumbnails)  %>
            <% image = issue.attachments.select(&:thumbnailable?).last %>
            <% if image %>
            <div class="thumbnail" style="background-image: url('<%= thumbnail_path(image, :size => 250) %>')">
            </div>
            <% end %>
          <% end %>
          <!-- Check list -->
          <% if @query.has_column_name?(:checklists) && show_checklist?(issue) %>
            <div class="checklist" id="checklist_<%= issue.id %>">
              <ul id="checklist_items">
                <% issue.checklists.each do |checklist_item| %>
                  <%= render :partial => 'checklists/checklist_item', :object => checklist_item %>
                <% end %>
              </ul>
              <script type="text/javascript">
                $("#checklist_<%= issue.id %>").checklist();
              </script>
            </div>
          <% end %>
          <% if @query.has_column_name?(:assigned_to) %>
            <p class="info assigned-user" style="<%= 'display: none;' unless issue.assigned_to %>">
              <span class="user"><%= avatar(issue.assigned_to, :size => "14").to_s.html_safe + " " + link_to_user(issue.assigned_to) if issue.assigned_to %></span>
            </p>
          <% end %>

          <% if @query.has_column_name?(:done_ratio) %>
            <%= progress_bar(issue.done_ratio, :width => '100%') %>
          <% end %>

          <% if (last_comment = @query.issue_last_comment(issue, :inline_adding => @inline_adding)) %>
            <em class="info description last_comment" title='<%= last_comment.user.to_s + " " + format_date(last_comment.created_on) %>'>
              <span class="icon icon-comment last-comment">
                <%= last_comment.notes.truncate(100) %>
              </span>
            </em>
          <% end %>
          <% if User.current.allowed_to?(:edit_issues, @project, :global => true) && RedmineAgile.allow_inline_comments? %>
            <div class="quick-comment">
            </div>
          <% end %>
      </span>
    <% end %>
</div>
<% if User.current.allowed_to?(:edit_issues, @project, :global => true) && @update %>
  <script type="text/javascript">

    document.onkeydown = function(evt) {
        evt = evt || window.event;
        if (evt.keyCode == 27) {
            $('html.agile-board-fullscreen').removeClass('agile-board-fullscreen');
            $(".issue-card").addClass("hascontextmenu");
            saveFullScreenState();
        }
    };

    $("table.issues-board thead").html("<%=escape_javascript render_board_headers(@query.board_statuses) %>");
  </script>

  <% if @error_msg %>
    <script type="text/javascript">
      setErrorMessage("<%= @error_msg%>", 'warning');
    </script>
  <% end %>

  <% if @update %>
    <script type="text/javascript">
      $("table.issues-board thead").html("<%=escape_javascript render_board_headers(@query.board_statuses) %>");
    </script>
    <% if Redmine::VERSION.to_s > '2.4' %>
      <script type="text/javascript">
        agileBoard.initDroppable();
        $("td.issue-status-col[data-id=<%= issue.status.id %>]").removeClass("over_wp_limit under_wp_limit");
        $("td.issue-status-col[data-id=<%= issue.status.id %>]").addClass("<%= @wp_class %>");
        <% if @old_status %>
          $("td.issue-status-col[data-id=<%= @old_status.id %>]").removeClass("over_wp_limit under_wp_limit");
          $("td.issue-status-col[data-id=<%= @old_status.id %>]").addClass("<%= @wp_class_for_old_status %>");
        <% end %>
      </script>
    <% end %>
    <% if @not_in_scope %>
      <script type="text/javascript">
        $(".issue-card[data-id='<%= issue.id %>']").toggle( "highlight" );
      </script>
    <% end %>
  <% end %>
  <%= init_agile_tooltip_info %>
<% end %>

app/views/agile_boards/_issue_tooltip.html.erb
<%= render_issue_tooltip @issue %>

app/views/agile_boards/_issues_links.html.erb
<h3><%= l(:label_issue_plural) %></h3>

  <ul>
  <li><%= link_to l(:label_issue_view_all), _project_issues_path(@project, :set_filter => 1) %></li>
  <% if @project %>
  <li><%= link_to l(:field_summary), project_issues_report_path(@project) %></li>
  <% end %>

  <% if User.current.allowed_to?(:view_calendar, @project, :global => true) %>
  <li><%= link_to l(:label_calendar), _project_calendar_path(@project) %></li>
  <% end %>
  <% if User.current.allowed_to?(:view_gantt, @project, :global => true) %>
  <li><%= link_to l(:label_gantt), _project_gantt_path(@project) %></li>
  <% end %>
  <% if User.current.allowed_to?(:view_agile_queries, @project) %>
  <li><%= link_to l(:label_agile_board), {:controller => "agile_boards", :action => "index", :project_id => @project} %></li>
  <% end %>
  <% if User.current.allowed_to?(:manage_agile_verions, @project) %>
  <li><%= link_to l(:label_agile_version_planning), {:controller => "agile_versions", :action => "index", :project_id => @project} %></li>
  <% end %>
  </ul>

app/views/agile_boards/_issues_sidebar.html.erb
<% if User.current.allowed_to?(:view_agile_queries, @project, :global => true) %>
  <%= link_to l(:label_agile_board), {:controller => "agile_boards", :action => "index", :project_id => @project} %>
  <br>
<% end %>
<% if User.current.allowed_to?(:manage_agile_verions, @project) && @project.versions.open.any? %>
  <%= link_to l(:label_agile_version_planning), {:controller => "agile_versions", :action => "index", :project_id => @project} %>
  <br>
<% end %>

app/views/agile_boards/index.js.erb
$('#content').html('<%= j(render('index')) %>')
$('table.issues-board').StickyHeader();
<%= init_agile_tooltip_info(:only_code => true) %>

app/views/agile_boards/inline_comment.html.erb
<%= text_area_tag "issue[notes]", "", :cols => 60, :rows => 5, :class => 'wiki-edit', :no_label => true %>
<button type="button" onclick="agileBoard.saveInlineComment(this, '<%= update_agile_board_path(:id => @issue) %>'); return false;">  <%= l(:button_submit) %> </button>
<%= link_to l(:button_cancel), "#", :onclick => "cancelInlineComment(this);return false;" %>